'use strict';
const originalHead=document.querySelector('#financial-table thead').innerHTML;
const $=id=>document.getElementById(id), C=window.HIERARCHY_CATALOG, P=window.HIERARCHY_PUBLICATION;
let A=null, activeAxis=null,
 D=null, table=null, displayRows=[], collapsed=new Set(), conceptFilter=null, hideBlanks=true;
const money=s=>{const [integer,fraction]=String(s).split(".");return integer.replace(/\B(?=(\d{3})+(?!\d))/g,",")+(fraction!==undefined?"."+fraction:"")};
const reasonLabel={TOP_3_COMPARABLE_AMOUNT:'상위 금액 3개',REVIEWED_SHARE_AT_LEAST_10_PERCENT:'검토 구성비 ≥ 10%',REVIEWED_SHARE_CHANGE_AT_LEAST_5_PP:'구성비 변화 ≥ 5%p',YOY_25_PERCENT_AND_PARENT_SCALE_1_PERCENT:'증감 ≥ 25% · 변화규모 ≥ 1%'};
const criticalWarning=w=>/SIGN|BASE|BASIS|SCOPE|INCOMPATIBLE|SCALAR_UNAVAILABLE|REVIEW_REQUIRED|BLOCK|QUARANTINE/.test(w);
const names={IS:'손익계산서',BS:'재무상태표',CF:'현금흐름표',DISCLOSURE:'공시 주석'};
const short=s=>(s||'').split(':').slice(-1)[0].replace(/([a-z])([A-Z])/g,'$1 $2');
const text=(tag,value,cls)=>{let e=document.createElement(tag);e.textContent=value??'';if(cls)e.className=cls;return e};
function option(select,value,label){const o=text('option',label);o.value=value;select.append(o)}
function sourceURL(f){return `https://www.sec.gov/Archives/edgar/data/${f.cik.replace(/^0+/,'')}/${f.accession.replaceAll('-','')}/${f.primary_document}`}
function periodLabel(p){return p.class==='INSTANT'||p.instant?`${p.class||'INSTANT'} · ${p.instant||p.end} (시점)`:`${p.class||''} · ${p.start?p.start+' → ':''}${p.end||''} (종료일 제외)`}
function valuesCell(facts){const el=text('div','','values');for(const f of facts){const p=f.scope?.period||{};const v=text('span',f.value_numeric===null?'— 미준비':money(f.value_numeric),'value');v.dataset.factId=f.fact_id;v.dataset.rawValue=f.value_numeric??'';
 v.append(text('small',periodLabel(p)));v.append(text('small',(f.scope?.unit?.numerator||[]).join(' × ')+(f.scope?.unit?.denominator?.length?' / '+f.scope.unit.denominator.join(' × '):'')));
 if(f.scope?.dimensions?.length)v.append(text('small',f.scope.dimensions.map(d=>`${short(d.axis_qname)}: ${short(d.member_qname)||d.typed_value}`).join(' / ')));el.append(v)}return el}
function inspect(payload){$('inspector').hidden=false;$('inspection').replaceChildren();
 if(payload.facts)for(const f of payload.facts){const block=text('section','','evidence-block');block.append(text('h3',f.concept?.qname||f.fact_id));let a=text('a',`${f.filing.form} · ${f.filing.accession} 원문`);a.href=sourceURL(f.filing);a.target='_blank';a.rel='noopener noreferrer';block.append(a);block.append(text('pre',JSON.stringify(f,null,2)));$('inspection').append(block)}
 for(const [key,value] of Object.entries(payload)){if(key==='facts')continue;const block=text('section','','evidence-block');block.append(text('h3',key),text('pre',JSON.stringify(value,null,2)));$('inspection').append(block)}}
window.axisLoaded=()=>{if(window.AXIS_COMPANY!==$('company').value)return;A=window.AXIS_DATA;render()};
function loadAnalyticalControls(){const info=C[$('company').value];$('metric').replaceChildren();option($('metric'),'','전체 재무 항목');for(const r of info.overview.rows)option($('metric'),r.row_id,r.label);loadAnalyticalAxes()}
function loadAnalyticalAxes(){const info=C[$('company').value];$('analytical-axis').replaceChildren();option($('analytical-axis'),'','기본 항목');for(const lens of info.axis_lenses||[])if(lens.anchor_row_id===$('metric').value)option($('analytical-axis'),lens.node_id,lens.label)}
function loadCompany(){A=null;loadAnalyticalControls();const axisScript=document.createElement('script');axisScript.src=C[$('company').value].axis_path;document.body.append(axisScript);const info=C[$('company').value];$('filing').replaceChildren();for(const f of info.filings)option($('filing'),f.filing.filing_id,`${f.filing.report_date} · ${f.filing.form} / 제출 ${f.filing.filed_date}`);
 $('warnings').replaceChildren(...info.warnings.map(w=>text('span',w)));loadFiling()}
function loadFiling(){const info=C[$('company').value].filings.find(f=>f.filing.filing_id===$('filing').value);D=null;$('rows').replaceChildren();$('title').textContent='준비 데이터 여는 중…';const script=document.createElement('script');script.src=info.path;script.onerror=()=>{$('title').textContent='준비된 파일을 열 수 없습니다.'};document.body.append(script)}
window.hierarchyLoaded=()=>{D=window.HIERARCHY_DATA;conceptFilter=null;$('statement').replaceChildren();for(const t of D.tables)option($('statement'),t.table_id,`${names[t.section]} · 표 ${t.table_order+1} / ${t.row_count}행`);const primary=D.tables.find(t=>t.section==='IS')||D.tables[0];$('statement').value=primary.table_id;loadAxes();render()};
function loadAxes(){const active=$('axis').value;$('axis').replaceChildren();option($('axis'),'','Axis 선택');for(const a of D.axes.axes){const members=a.members.filter(m=>!conceptFilter||D.members[JSON.stringify([a.axis_id,m.member_id,m.typed_value])].facts.some(f=>f.raw_concept_id===conceptFilter));if(members.length)option($('axis'),a.axis_id,short(a.qname))}if([...$('axis').options].some(o=>o.value===active))$('axis').value=active;loadMembers()}
function loadMembers(){const a=D.axes.axes.find(x=>x.axis_id===$('axis').value);$('member').replaceChildren();option($('member'),'','Member 선택');if(a)for(const m of a.members){const key=JSON.stringify([a.axis_id,m.member_id,m.typed_value]);if(!conceptFilter||D.members[key].facts.some(f=>f.raw_concept_id===conceptFilter))option($('member'),key,short(m.qname)||m.typed_value)}$('lens-warning').textContent=conceptFilter?'선택한 재무 항목의 공시 차원 · Axis 간 합산 없음':'독립 관점 · 전체 차원 보존 · 자동 합산 없음'}
function sourceRows(panel){const facts=new Map(panel.facts.map(f=>[f.fact_id,f]));const importance=new Map(panel.importance.map(i=>[i.current_fact_id,i]));return panel.rows.map(r=>{const ids=[...new Set(r.cells.flatMap(c=>c.inline_facts.map(i=>i.fact_id)).filter(Boolean))];const fs=ids.map(i=>facts.get(i)).filter(Boolean);return {id:r.row_id,parent:r.parent_row_id,depth:r.depth,label:r.label,protected:r.protected,facts:fs,importance:ids.map(i=>importance.get(i)).filter(Boolean),checks:panel.checks.filter(c=>ids.includes(c.parent_fact_id)),source:r,layoutBlank:r.cells.every(c=>!c.text&&!c.inline_facts.length),warnings:[...(r.warnings||[]),...ids.flatMap(i=>(importance.get(i)?.warnings||[]).filter(criticalWarning))]}})}
function preRows(panel){return (D.pre[table.table_id]||[]).map(r=>{
 const importance=panel.importance.filter(i=>r.facts.some(f=>f.fact_id===i.current_fact_id));
 return {id:r.row_id,parent:r.parent_row_id,depth:r.depth,label:short(r.concept.qname),protected:r.protected,facts:r.facts,importance,checks:panel.checks.filter(c=>r.facts.some(f=>f.fact_id===c.parent_fact_id)),source:r,warnings:[...new Set([...(r.warnings||[]),...(r.cycle?['PRE_CYCLE_TERMINATED']:[]),...importance.flatMap(i=>(i.warnings||[]).filter(criticalWarning))])]}
})}
function memberRows(){const key=$('member').value;const result=D.members[key];if(!result)return[];const selected=JSON.parse(key);const paths=D.member_paths.filter(p=>p.axis_id===selected[0]);const out=paths.map(p=>({id:p.member_path_id,parent:p.parent_path_id,depth:p.depth,label:short(p.member.qname),protected:p.cycle,facts:[],importance:[],checks:[],source:p,warnings:p.cycle?['DEF_CYCLE_TERMINATED']:p.usable?[]:['MEMBER_NOT_USABLE']}));
 const parents=paths.filter(p=>p.member_id===selected[1]&&p.usable&&!p.cycle);const selectedParent=parents[0];
 const fs=result.facts.filter(f=>!conceptFilter||f.raw_concept_id===conceptFilter);
 const metricRows=[];for(const f of fs)metricRows.push({id:'metric:'+f.fact_id,parent:selectedParent?.member_path_id||null,depth:selectedParent?selectedParent.depth+1:0,label:short(f.concept.qname),protected:false,facts:[f],importance:[],checks:[],source:{status:result.status,full_scope:f.scope},warnings:[]});
 const position=selectedParent?out.findIndex(r=>r.id===selectedParent.member_path_id)+1:out.length;out.splice(position,0,...metricRows);return out}
function analyticalRows(){const info=C[$('company').value], overview=info.overview;return overview.rows.filter(r=>!$('metric').value||r.row_id===$('metric').value).map(r=>{const cells=overview.cells.filter(c=>c.row_id===r.row_id);return{id:'analytical:'+r.row_id,parent:null,depth:0,label:r.label,protected:true,facts:[],importance:[],checks:[],source:{row:r,cells,traces:cells.map(c=>info.traces?.[c.cell_id]).filter(Boolean),metrics:overview.metrics.filter(m=>m.row_id===r.row_id),policy:info.importance.policy,importance:info.importance.records.filter(i=>cells.some(c=>c.cell_id===i.current_cell_id))},warnings:[],metric_id:r.row_id,analytical:cells}})}
function render(){if(!D)return;document.querySelector('#financial-table thead').innerHTML=originalHead;table=D.tables.find(t=>t.table_id===$('statement').value);collapsed.clear();$('depth').value='all';const panel=D.panels[table.table_id];const member=$('explore').value==='member', analytical=!member&&$('mode').value==='analytical';
 activeAxis=analytical&&A?A[$('analytical-axis').value]:null;
 $('analytical-controls').hidden=!analytical;$('source-controls').hidden=analytical;
 $('value-title').textContent=analytical?'준비된 분석 값 · 보고/파생 구분':'공시 값 · Raw 원금액';
 $('filing').disabled=analytical;$('statement').disabled=analytical;$('axis').disabled=!member;$('member').disabled=!member;
 for(const id of ['filing','statement'])$(id).title=analytical?'기업 발행본 전체 비교에서는 적용되지 않습니다.':'';
 displayRows=member?memberRows():analytical?(activeAxis?axisRows(activeAxis):analyticalRows()):$('mode').value==='pre'?preRows(panel):sourceRows(panel);
 const info=C[$('company').value];$('warnings').replaceChildren(...[...info.warnings,...(analytical?[...info.overview.warnings,...(activeAxis?.warnings||[])]:[])].map(w=>text('span',w)));
 $('title').textContent=member?'세그먼트 · 공시된 지표':analytical?(activeAxis?'전체 구성 · '+activeAxis.lens.label:'기업 발행본 · 준비된 Analytical 기간 비교'):names[table.section];
 const header=$('period-header');header.replaceChildren();
 if(analytical){const ctx=info.overview.context, periods=ctx.periods, label=p=>`FY${p[0]} Q${p[1]}`;
  $('scope').textContent=`기업 발행본 전체 · ${ctx.ticker} · view ${ctx.view} | 공시 선택 기준 as_of ${ctx.as_of} | 원본 검토 기준 cutoff ${ctx.review_cutoff||'없음'} | 기간 ${periods.length?label(periods[0])+' ~ '+label(periods[periods.length-1]):'미준비'} | 과거 공시 시점 조회가 아닙니다. 재작성 비교가능성은 각 준비 근거를 확인하세요.`;
  $('coverage').textContent=(activeAxis?`전체 ${activeAxis.rows.length-1}개 준비 행 · 서로 다른 매핑 기간은 별도 행 · 전체 Member를 동시 가산하지 않음 · 산식은 표시된 정확한 기간에만 적용 | Axis 발행 ${activeAxis.publication.axis_publication_id||'검토 없음'} · 결정 ${activeAxis.publication.axis_decision_cutoff||'없음'} | `:'')+`Analytical 발행 ${ctx.publication_id} · 준비된 ${periods.length}분기 · ${info.overview.rows.length}항목 | 원본 발행 ${ctx.source_publication} | 구성비 정책 ${P.policy.version}`;
  $('financial-table').style.setProperty('--period-count',Math.min(periods.length||1,8));
  for(const p of periods)header.append(text('span',label(p)));
 }else{
  $('scope').textContent=`보고 ${D.filing.report_date} · 제출 ${D.filing.filed_date} · ${D.filing.accession} | ${member?'선택 공시의 독립 Axis / 전체 차원':$('mode').value==='pre'?'PRE 순서 (원문 HTML 순서와 별도)':table.table_locator}`;
  $('coverage').textContent=`원문 표 ${table.row_count}행 · 포함 ${panel.rows.filter(r=>r.coverage_status==='INCLUDED').length} · 구조 ${panel.rows.filter(r=>r.coverage_status==='STRUCTURAL').length} · 미준비 ${panel.rows.filter(r=>r.coverage_status==='UNPREPARED').length} | PRE ${panel.pre_rows.length}경로 · HTML 미대응 PRE ${panel.pre_not_in_html.length}경로. 구성비 정책 ${P.policy.version}`;
  const best=displayRows.filter(r=>r.facts.length).sort((a,b)=>b.facts.length-a.facts.length)[0];const count=Math.min(best?.facts.length||4,8);$('financial-table').style.setProperty('--period-count',count);if(best)for(const f of best.facts.slice(0,count))header.append(text('span',periodLabel(f.scope.period)));
 }
 configureColumns(analytical);renderSourceComparison(activeAxis);draw()}
function draw(){const tbody=$('rows');tbody.replaceChildren();const parents=new Set(displayRows.map(r=>r.parent).filter(Boolean));
 for(const r of displayRows){const tr=document.createElement('tr');tr.dataset.rowId=r.id;tr.dataset.parentId=r.parent||'';tr.dataset.depth=r.depth;tr.dataset.protected=String(r.protected);if(r.protected&&r.facts.length)tr.classList.add('total');if(!r.facts.length)tr.classList.add('structural');if(r.importance.some(i=>i.is_reference_period!==false&&i.reasons?.length))tr.classList.add('important');
 const label=document.createElement('td'),wrap=text('div','','label');wrap.style.paddingLeft=(r.depth*16)+'px';if(parents.has(r.id)){const b=text('button',collapsed.has(r.id)?'▸':'▾','toggle');b.setAttribute('aria-label',r.label+' 펼치기/접기');b.setAttribute('aria-expanded',String(!collapsed.has(r.id)));b.onclick=()=>{collapsed.has(r.id)?collapsed.delete(r.id):collapsed.add(r.id);draw()};wrap.append(b)}else wrap.append(text('span','·','toggle'));wrap.append(text('span',r.label),text('span',`D${r.depth}`,'depth-tag'));label.append(wrap);if(r.scopeLabel)label.append(text('small',r.scopeLabel,'epoch-scope'));tr.append(label);
 if(r.analytical){for(const c of alignedCells(r)){const td=document.createElement('td');td.className='quarter-cell';td.append(analyticalValue(c));for(const check of r.checks.filter(k=>k.period?.start===c.start&&k.period?.end===c.end)){const badge=text('small',`${check.child_row_ids.length}개 직접 구성 · ${check.validation_status==='MATCH'?'합계 일치':check.validation_status} · Δ ${check.difference}`,'equation');badge.title=check.formula||'';td.append(badge)}td.onclick=()=>inspect({cell:c,provenance:c.provenance||C[$('company').value].traces?.[c.cell_id],row:r.source});tr.append(td)}}else{
 const value=document.createElement('td');value.append(valuesCell(r.facts));if(!r.facts.length&&r.source?.cells)value.append(text('span',r.source.cells.map(c=>c.text).filter(Boolean).join(' | '),'source-text'));if(r.analytical)for(const c of r.analytical){const v=text('span',`${c.value!==null?money(c.value):'—'} · FY${c.fiscal_year} Q${c.fiscal_quarter} ${c.period_class} `,'value');v.dataset.cellId=c.cell_id;v.dataset.rawValue=c.value??'';v.dataset.sourceStatus=c.status??'';v.append(text('small',`${({REPORTED:'보고',DERIVED:'파생',UNAVAILABLE:'미준비'})[c.status]||'상태'} · ${c.status??'미준비'}`,'origin-status'));value.append(v)}tr.append(value);}
 const proof=document.createElement('td');for(const reason of new Set(r.importance.filter(i=>i.is_reference_period!==false).flatMap(i=>i.reasons||[])))proof.append(text('span',reasonLabel[reason]||reason,'badge'));for(const c of r.checks)proof.append(text('span',`${c.relationship_type==='REVIEWED_SOURCE_RECONCILIATION'?'원문 조정 ':''}${c.status} / Δ ${c.difference_calculated_minus_reported??'—'}`,'badge'+(c.status==='MATCH'?'':' warn')));for(const warning of r.warnings)proof.append(text('span',warning,'badge warn'));
 const b=text('button','산식 · 중요도 · 출처','proof');b.onclick=()=>inspect({facts:r.facts,source_row:r.source,calculation_checks:r.checks,importance_v2:r.importance,policy:P.policy});proof.append(b);
 if(r.metric_id&&(C[$('company').value].axis_lenses||[]).some(l=>l.anchor_row_id===r.metric_id)){const explore=text('button','구성 보기','proof composition-entry');explore.onclick=()=>{$('metric').value=r.metric_id;loadAnalyticalAxes();const lenses=$('analytical-axis').options;if(lenses.length>1)$('analytical-axis').selectedIndex=1;render()};label.append(explore)}
 if(r.facts.length){const explore=text('button','항목 → Axis','proof');explore.onclick=()=>{conceptFilter=r.facts[0].raw_concept_id;$('explore').value='member';loadAxes();render()};proof.append(explore)}tr.append(proof);tbody.append(tr)}visibility()}
function visibility(){const byId=new Map(displayRows.map(r=>[r.id,r]));let hidden=0;for(const r of displayRows){let hide=false,p=r.parent,seen=new Set();while(p&&!seen.has(p)){seen.add(p);if(collapsed.has(p))hide=true;p=byId.get(p)?.parent}if($('depth').value!=='all'&&r.depth>Number($('depth').value))hide=true;if(r.protected||r.warnings.length)hide=false;if(hideBlanks&&r.layoutBlank)hide=true;const tr=[...$('rows').children].find(e=>e.dataset.rowId===r.id);if(tr)tr.hidden=hide;if(hide)hidden++}$('hidden-count').textContent=`접힌 항목 ${hidden} / 전체 ${displayRows.length}`}
$('source-comparison-jump').onclick=()=>$('source-comparison').scrollIntoView({behavior:'smooth',block:'start'});
$('metric').onchange=()=>{loadAnalyticalAxes();render()};$('analytical-axis').onchange=render;
$('company').onchange=loadCompany;$('filing').onchange=loadFiling;$('statement').onchange=render;$('mode').onchange=()=>{if($('mode').value==='analytical')$('explore').value='statement';render()};$('explore').onchange=()=>{if($('explore').value==='member'&&$('mode').value==='analytical')$('mode').value='source';render()};$('axis').onchange=()=>{loadMembers();render()};$('member').onchange=render;$('all-concepts').onclick=()=>{conceptFilter=null;loadAxes();render()};$('close-inspector').onclick=()=>$('inspector').hidden=true;
$('collapse').onclick=()=>{collapsed=new Set(displayRows.map(r=>r.parent).filter(Boolean));draw()};$('restore').onclick=()=>{collapsed.clear();hideBlanks=false;$('blank-toggle').textContent='빈 레이아웃 행 숨기기';$('depth').value='all';draw()};$('blank-toggle').onclick=()=>{hideBlanks=!hideBlanks;$('blank-toggle').textContent=hideBlanks?'빈 레이아웃 행 표시':'빈 레이아웃 행 숨기기';visibility()};$('depth').onchange=visibility;
$('pub').textContent=`발행 ${P.id}${P.renderer_source_commit?' · 화면 소스 '+P.renderer_source_commit.slice(0,12):''} · 결정 기준시점 ${P.decision_cutoff} · ${P.policy.version}`;
for(const ticker of Object.keys(C))option($('company'),ticker,ticker);$('company').value=Object.keys(C)[0];loadCompany();
function axisRows(a){return a.rows.map(r=>({id:r.row_id,parent:r.parent_row_id,depth:r.depth,label:r.label,scopeLabel:r.row_kind==='TOTAL'?'기준 총액 · 전체 행의 합을 의미하지 않음':`관측 ${(r.observed_periods||[]).map(p=>'FY'+p[0]+' Q'+p[1]).join(', ')||'미준비'} · ${r.mapping_review_required?'매핑 검토 필요':'기존 매핑 범위'} · basis ${r.basis_version||'미지정'} · 행 ${r.row_id.slice(0,8)}`,protected:!!r.protected,facts:[],importance:[...(r.importance_v2||[]),{reasons:r.importance_reasons||[]}],checks:a.reviewed_relationships.filter(c=>c.display_scope==='ANALYTICAL_EXACT_MATCH'&&c.parent_row_id===r.row_id).map(c=>({...c,status:c.validation_status,difference_calculated_minus_reported:c.difference})),source:{...r,reviewed_relationships:a.reviewed_relationships,publication:a.publication},warnings:r.warnings||[],analytical:r.cells}))}
function alignedCells(r){const periods=C[$('company').value].overview.context.periods;return periods.map(([year,quarter])=>r.analytical.find(c=>c.fiscal_year===year&&c.fiscal_quarter===quarter)||{fiscal_year:year,fiscal_quarter:quarter,period_class:r.source?.row?.period_class||activeAxis?.period_class,status:'UNAVAILABLE',value:null,reason:'PERIOD_NOT_DISCLOSED_FOR_PREPARED_ROW_IDENTITY'})}
function analyticalValue(c){const v=text('span',c.value==null?'— 미준비':money(c.value),'value');v.dataset.cellId=c.cell_id||'';v.dataset.rawValue=c.value??'';v.dataset.sourceStatus=c.status||'UNAVAILABLE';v.dataset.factId=c.source_fact_id||'';v.append(text('small',`${c.period_class} · ${({REPORTED:'보고',DERIVED:'파생',UNAVAILABLE:'미준비'})[c.status]||''} · ${c.status||'UNAVAILABLE'}`,'origin-status'));if(c.start||c.end)v.append(text('small',periodLabel({class:c.period_class,start:c.start,end:c.end})));v.title=c.reason||'셀을 눌러 출처 확인';return v}
function configureColumns(analytical){const table=$('financial-table');table.classList.toggle('timeseries',analytical);if(!analytical){table.style.removeProperty('width');return}const head=table.querySelector('thead tr'),periods=C[$('company').value].overview.context.periods;head.replaceChildren();const first=text('th','재무 항목 / 독립 매핑 행');first.append(text('small','준비된 분석 값 · 보고/파생 구분'));first.lastChild.id='value-title';head.append(first);for(const [year,quarter] of periods){const th=text('th',`FY${year} Q${quarter}`);th.dataset.period=`${year}-${quarter}`;head.append(th)}head.append(text('th','중요도 · 검토 산식 · 출처'));table.style.width=(360+periods.length*190+340)+'px'}
function renderSourceComparison(a){const host=$('source-comparison');host.replaceChildren();host.hidden=!a?.source_comparisons?.length;$('source-comparison-jump').hidden=host.hidden;if(host.hidden)return;host.append(text('h3','별도 원문 비교 · 같은 공시의 보고된 두 QTD 기간'),text('p','이 값은 위의 역사적 Analytical 선택을 대체하지 않습니다.'));
 for(const comparison of a.source_comparisons){const filing=comparison.table.filing;const context=text('div','','source-comparison-context');context.append(text('p',`${filing.form} · ${filing.accession} · 보고 ${filing.report_date} · 제출 ${filing.filed_date}`));const link=text('a','해당 공시 원문');link.href=sourceURL(filing);link.target='_blank';link.rel='noopener noreferrer';context.append(link,text('small',` · Axis 검토 발행 ${comparison.publication.axis_publication_id} · 결정 ${comparison.publication.axis_decision_cutoff}`));host.append(context);const scroll=text('div','','scroll'),t=text('table','','timeseries source-comparison-table'),head=text('thead',''),tr=text('tr','');tr.append(text('th','원문 항목'));for(const c of comparison.columns)tr.append(text('th',periodLabel({class:c.period_class,start:c.start,end:c.end})));head.append(tr);t.append(head);const body=text('tbody','');for(const row of comparison.rows){const r=text('tr','');r.dataset.rowId=row.row_id;const label=text('td',row.label);label.style.paddingLeft=(16+row.depth*24)+'px';r.append(label);for(const cell of row.cells){const td=text('td','');td.append(valuesCell(cell.fact?[cell.fact]:[]));td.onclick=()=>inspect({facts:cell.fact?[cell.fact]:[],source_comparison:comparison,reviewed_relationships:a.reviewed_relationships});r.append(td)}body.append(r)}t.append(body);scroll.append(t);host.append(scroll)}
 for(const check of a.reviewed_relationships){const b=text('button',`${check.formula||'검토 산식'} · ${check.display_scope} · ${check.period.start} → ${check.period.end} · ${check.validation_status} · Δ ${check.difference}`,'proof');b.onclick=()=>inspect({reviewed_equation:check,formula:`${check.parent_fact_id} = ${check.child_fact_ids.join(' + ')}`,approval_scope:a.publication});host.append(b)}}
